### ISSUE TITLE
Fabric (crashlytics) 설정 + slack 연동

### ISSUE THREAD

**Issue by babosamo** [teamtuna/OpenWeather#12]
fabric 에 계정 생성 (tuna team 계정으로 하면 될듯)
crashlytics (요즘은 play store migration 을 강제하더라고여)
slack 에 특정 채널 생성 후 연동

**Comment by eastar-dev** [comment]
제가 가져가서 작업 합니다.

**Comment by eastar-dev** [comment]
https://firebase.google.com/docs/crashlytics/get-started?platform=android
문서를 보면서 작업 하는데
요즘에는


```
class MyApplication : Application() {
    override fun onCreate() {
        super.onCreate()

        FirebaseAnalytics.getInstance(applicationContext)
        Fabric.with(this, Crashlytics())
```

이런코딩이 없어도 되나요?
활성화가 안되네요
시간이 걸리는건지?

https://console.firebase.google.com/project/openweather-35baf/crashlytics/app/android:com.karrel.openweather/issues
를 보면서 확인하고 있습니다.

[튜나계정>권한추가 후 이용가능](https://console.firebase.google.com/project/openweather-35baf/settings/iam)

**Comment by babosamo** [comment]
slack 연동 완료~!
